	<div class="row">
		<div class="col-xs-12">
		<h1>Submissão de Documentos</h1>
			<form action="app/upload.php" id="myForm" method="POST" enctype="multipart/form-data" >
				<div class="col-xs-10">
					<input type="text" name="titulo" class="form-control input-hg" placeholder="Titulo do Documento"/>
					<div class="form-group">
					  <input type="file" name="arquivo" class="form-control input-hg" />
					  <span class="input-icon fui-plus"></span>
					</div>
				</div>
				<div class="col-xs-2">
					<button class="btn btn-hg btn-primary glyphicon glyphicon-arrow-up" style="font-size:65px;"></button>
				</div>
			</form>
		</div>
	
		<div class="col-xs-12">
		<?php $i=0;while($i<20){?>
			<div class="col-xs-2">
				<div class="tile" style="margin:5px;padding:0px;">
					<i class="tile-image glyphicon glyphicon-file" style="font-size:65px;margin-bottom:0;"></i>
					<h3 class="tile-title">Arquivo</h3>
					<p>Usuario Dono</p>
				  </div>
			</div>
		<?php $i++;} ?>
		</div>
      </div>