<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ALVO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Loading Bootstrap -->
    
    <?php $this->headLink()->appendStylesheet('/bootstrap/css/bootstrap.css')?>
    <?php $this->headLink()->appendStylesheet('/bootstrap/css/prettify.css')?>
    <?php $this->headLink()->appendStylesheet('/css/flat-ui.css')?>
    <?php $this->headLink()->appendStylesheet('/bootstrap/css/bootstrap.css')?>
    
    <?php echo $this->headLink()?>
    
    <?php $this->headScript()->appendFile('/js/jquery-1.8.3.min.js')?>
    <?php $this->headScript()->appendFile('/js/jquery-ui-1.10.3.custom.min.js')?>
    <?php $this->headScript()->appendFile('/js/jquery.ui.touch-punch.min.js')?>
    <?php $this->headScript()->appendFile('/js/bootstrap.min.js')?>
    <?php $this->headScript()->appendFile('/js/bootstrap-select.js')?>
    <?php $this->headScript()->appendFile('/js/bootstrap-switch.js')?>
    <?php $this->headScript()->appendFile('/js/flatui-checkbox.js')?>
    <?php $this->headScript()->appendFile('/js/flatui-radio.js')?>
    <?php $this->headScript()->appendFile('/js/jquery.tagsinput.js')?>
    <?php $this->headScript()->appendFile('/js/jquery.placeholder.js')?>
    <?php $this->headScript()->appendFile('/js/typeahead.js')?>
    <?php $this->headScript()->appendFile('/bootstrap/js/google-code-prettify/prettify.js')?>
    <?php $this->headScript()->appendFile('/js/application.js')?>
    <?php echo $this->headScript()?>
   <!-- <link href="css/docs.css" rel="stylesheet"-->
</head>