    <nav class="navbar navbar-default" role="navigation" style="background-color:#C0392B;border-radius: 0px;z-index: 1000;">
<style>ul *, .navbar-brand, b .caret{color: #F9FFF4 !important;}
.navbar-default .navbar-nav > .dropdown > a .caret {color: #F9FFF4 !important;border-bottom-color: #F9FFF4 !important; border-top-color: #F9FFF4 !important;}
</style>
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ALVO</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" ><span class="fui-plus"></span></a></li>
        <li><a href="#" ><span class="fui-chat"></span></a></li>
        <li><a href="#" ><span class="fui-time"></span></a></li>
    
     
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>