  <style>
.sidebar {
  display: none;
}
@media (min-width: 768px) {
  .sidebar {
    position: fixed;
    top: 51px;
    bottom: 0;
    left: 0;
    z-index: 999;
    display: block;
    padding: 20px;
    overflow-x: hidden;
    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
    background-color: #BDC3C7;
    border-right: 1px solid #eee;
    
  }
}

/* Sidebar navigation */
.nav-sidebar {
  margin-right: -21px; /* 20px padding + 1px border */
  margin-bottom: 20px;
  margin-left: -20px;
}
.nav-sidebar > li > a {
  padding-right: 20px;
  padding-left: 20px;
  border-bottom: #eee thin;
}
.nav-sidebar > .active > a {
  color: #fff;
  background-color: #428bca;
}


</style>

        <ul class="nav nav-sidebar">
                <li><a><i class="glyphicon glyphicon-user"></i> Perfil</a></li>
                <li><a><i class="glyphicon glyphicon-envelope"></i> Mensagens</a></li>
                <li><a><i class="glyphicon glyphicon-pencil"></i> Projetos</a></li>
                <li><a><i class="glyphicon glyphicon-plus"></i> Tarefas</a></li>
        </ul>
