<?php echo $this->render('_header.phtml');?>
<body>
<?php echo $this->render('_navigation.phtml');?>
    

<div class="container-fluid">
    <div class="col-sm-3 col-md-2 sidebar">
        <?php echo $this->render('_sidebar.phtml');?>
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <?php echo $this->layout()->content; ?>
    </div>
    
</div>

</body>